#!/bin/sh
BATTERY='/sys/bus/acpi/drivers/battery/PNP0C0A:00/power_supply/BAT0'
CPU='/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq'
main() {
    # show numbers with param, icons without
    if [ -n "$1" ]; then
      shownumber=1
    else
      shownumber=0
    fi
    capacity=$(cat $BATTERY/capacity)
    status=$(cat $BATTERY/status)
    cpuspeed=$(($(cat $CPU)/1000))
    if [ 1 = "$shownumber" ] ; then
      icon="$capacity"
      cpupart="@${cpuspeed} "
    else
      icon=$(block ${capacity})
      cpupart=""
    fi
    echo ${capacity} >&2
    case ${status} in
        "Discharging") echo -n "${icon}🠛" ;;
        "Charging") echo -n "${icon}🠙" ;;
        *) echo -n "${icon}" ;;
    esac
    echo -n "$cpupart"
}

block() {
    if [ ${1} -gt 87 ]; then echo -n '█';
    elif [ ${1} -gt 75 ]; then echo -n '▇';
    elif [ ${1} -gt 62 ]; then echo -n '▆';
    elif [ ${1} -gt 50 ]; then echo -n '▅';
    elif [ ${1} -gt 37 ]; then echo -n '▄';
    elif [ ${1} -gt 25 ]; then echo -n '▃';
    elif [ ${1} -gt 12 ]; then echo -n '▂';
    elif [ ${1} -gt 6 ]; then echo -n '▁';
    else echo '_';
    fi
}

main "$1"
