#!/bin/bash
if pgrep -u $USER -f emacs > /dev/null;
then
	nohup  emacsclient "$@" > /dev/null 2>&1 &
	sleep 1		
        xdotool windowactivate $(xdotool search --class emacs | tail -1) > /dev/null 2>&1 &
else
	nohup  bash -c "emacs $@" > /dev/null / 2>&1 &
fi
