#!/bin/sh
# Export the dbus session address on startup so it can be used by any other environment
sleep 5

OUTPUT=$HOME/.Xdbus
touch $OUTPUT
chmod 600 $OUTPUT
echo '' > $OUTPUT

emit () {
  env | grep $1 >> $OUTPUT
  echo "export $1" >> $OUTPUT
}

for VAR in DBUS_SESSION_BUS_ADDRESS XAUTHORITY \
           SSH_AGENT_PID SSH_AUTH_SOCK; do
  emit $VAR
done	

## What to do with this? For example:

# 1. Register a script for the laptop lid event
#     $ cat /etc/acpi/events/lm_lid
#     event=button/lid.*
#     action=/etc/acpi/lid.sh
#2. Run slock to lock screen, bypassing *-power-manager bullshit
#      $ cat /etc/acpi/lid.sh
#      #!/bin/bash
#      source /home/p/.Xdbus
#      grep -q closed /proc/acpi/button/lid/LID/state
#      if [ $? = 0 ]
#      then
#      	DISPLAY=:0.0 su p -c "slock" &
#      else
#      	 echo	;
#      fi
