#!/bin/sh
# The egg mouse is super sensitive, even with the
# accel knobs turned to 0 in the GUI
# Setting up constant deceleration helps a lot.

SLEEPTIME=10

set_accel(){
    xinput --set-prop "HID 04d9:2082" "libinput Accel Speed" -0.9
}

get_accel(){
    xinput list-props "HID 04d9:2082" \
        | grep 'libinput Accel Speed (291)' \
        | awk '{print $5}'
}

if [ "" = "$1" ];
then set_accel ;  # one-shot mode
else              # monitor and set if needed
    while true; do
      ACCEL=$(get_accel)
      if [ "$ACCEL" = "0.000000" ]; then set_accel ; fi
      sleep "$SLEEPTIME"
    done
fi
