#!/bin/sh
set -x
ID="usb-CATEX_TECH._KB84M-S_CA2015040001-event-kbd"
DEV="/dev/input/by-id/${ID}"

renice +19 $$ >/dev/null

while (true) ; do
  sleep 2
  xmodmap ~/.Xmodmap
  inotifywait -q -e close -e open -e create -e delete ${DEV} #>/dev/null
done
