#!/bin/sh
CURRENT=$(xdotool getwindowfocus)
# ZOOM_AS=$(xdotool search --limit 1 --name "as_toolbar") #screenshare
ZOOM=$(xdotool search --limit 1 --name "Zoom Meeting ID:")
xdotool windowactivate --sync ${ZOOM}
sleep 0.1
xdotool key --clearmodifiers "alt+a"
sleep 0.1
xdotool windowactivate --sync ${CURRENT}
