#!/bin/bash
#CHRO=/home/p/.local/bin/chro

uchromium "$@" > /dev/null 2>&1

# if ! (pgrep -fl uchromium  > /dev/null 2>&1)
# then uchromium "$@" > /dev/null 2>&1
# else uchromium "$@" > /dev/null 2>&1
# fi
