#!/bin/sh
set -x

amixer set Master toggle
if (amixer get Master | grep Mono | grep '\[on\]'); then
  amixer set Headphone unmute
  amixer set Speaker unmute
  notify-send -t 3000 -i audio-volume-medium "Unmuted"
else
  amixer set Headphone mute
  amixer set Speaker mute
  notify-send -t 3000 -i audio-volume-muted "Muted"
fi

# Turn on all volumes, because they get silenced :<
amixer -q set Headphone 80%
amixer -q set PCM 100%
amixer -q set Speaker 100%
