#!/bin/sh
set -x
if [ -z "$1" ]; then
#  T=xfce4-terminal
   T=gnome-terminal	
else
  T=$1
fi	

pid=$(pgrep -fl "$T" | grep -v xfterm | grep -v grep | grep -v sh)
if [ -z "$pid" ]; then
  nohup  bash -c "$T" > /tmp/xfterm 2>&1 &
  sleep 3; exit 0
else
  W="$(xdotool search --class $T | tail -1)"
  xdotool windowactivate "$W"
  xdotool windowfocus "$W"
  exit 0
fi
