#!/bin/sh
set -x
T="${1:='xfce4-terminal'}"
pid=$(pgrep -fl "$T" | grep -v xfterm | grep -v grep)
if [ -z "$pid" ]; then
  nohup  bash -c "$T" > /dev/null / 2>&1 &
  sleep 3; exit 0
else
  W=$(xdotool search --class $T | tail -1)
  xdotool windowactivate "$W"
  xdotool windowfocus "$W"
  exit 0
fi
