#!/bin/env ruby
require 'uri'
(ARGV.length == 2) ? (puts "OK") : (raise "Usage: yt SSH_HOST URL")
host, url = ARGV[0], URI.parse(ARGV[1])
del = "\033[1G"
printf "#{del}Getting #{url} ... "
get_via_ssh = `ssh #{host} 'mkdir -p $HOME/yt && cd $HOME/yt && $HOME/.local/bin/youtube-dl -o "%(id)s_%(title)s.%(ext)s" #{url}'`
printf "#{del}Downloading file from #{host} ... "
scp_from_ssh = `scp #{host}:yt/* .`
printf "#{del}Deleting remote file   \n"
delete_via_ssh = `ssh #{host} 'rm -f $HOME/yt/*'`
printf "DONE"
